outputDir="{fullpath}" # Repositories output directory

[gitlab]
  hostURL="https://{host}" # API URL
  privateToken="{token}" # https://docs.gitlab.com/ce/api/README.html#private-tokens
  gitCloneURL="ssh://git@{host}:{port}" # SSH URL for 'git clone'
  branch="master" # checkout branch

[filter]
  targetNameSpaces="{namespace1},{namespace2}"
  excludeProjects="{out1},{out2},{out3}"
